:lang: no
:revdate: 2018-08-06
:title_en: National Architecture Repository Norway 
:title_no: Norsk fellesoffenltig arkitekturbibliotek
:keywords: Norsk, arkitekturbibliotek, offenlig sektor, virksomhetsarkitektur, NIF, samhandlingsarkitektur, GitHub
include::common/includes/standardheader.adoc[]
include::common/includes/commonlinks1.adoc[]

:url_hvordan_opprette_github_bruker: https://www.wikihow.com/Create-an-Account-on-GitHub[Tips om å opprette github bruker]

:link_praktiske_tips_komme_igang_med_innholdsproduksjon: link:getting_started/Praktiske_tips_for_å_komme_igang.adoc[Praktiske tips for å komme i gang med GitHub og bidra med innhold]

:link_dokumentasjonskonvensjoner: link:getting_started/dokumentasjonskonvensjoner.adoc[Dokumentasjonskonvensjoner]

:link_konsepter_og_prinsipper: link:getting_started/konsepter_og_prinsipper.adoc[Konsepter og prinsipper]



== Bakgrunn og formål
Dette GitHub-biblioteket er opprettet av Difi våren 2018 for å samle dokumentasjon om virksomhetsarkitektur i offentlig sektor i Norge.


Innholdet dreier seg primært om __samhandlingsarkitektur__, men er ikke begrenset til dette. All arkitekturdokumentasjon som kan være nyttig på tvers av virksomheter og sektorer hører hjemme her. 

I tillegg til innholdet i dette biblioteket, vil det finnes mye stoff i tilsvarende biblioteker i de enkelte virksomhetene som også kan være av felles interesse. Det er et siktemål at alle virksomheter følger et sett av  retningslinjer for arkitekturdokumentasjon som gjør det enkelt å referere og integrere innhold på tvers.

== Hvordan finne fram
Mappestrukturen i biblioteket er bygget opp etter mønster av {url_togaf_92} og {url_norsk_arkitekturrammeverk_for_samhandling}.

NOTE: Det er også lagt opp til å tagge innhold med metadata, for å støtte søk og alternative navigersmåter.


== Ditt bidrag er ønsket
Det legges opp til utstrakt samarbeid på tvers av av offentlig sektor for å etablere og vedlikeholde innhold i dette  arkitekturbiblioteket.

Terskelen for å publisere innhold skal ikke være for høy. Eksempler og praksis må deles for å få fram god praksis, anbefalinger, retningslinjer og standarder.

Gi beskjed via e-post til nasjonal_arkitektur@difi.no om du ønsker å bidra og vil ha skrivetilgang. Oppgi da ditt brukernavn på GitHub (se eventuelt {url_hvordan_opprette_github_bruker}).

Se også 

1. {link_praktiske_tips_komme_igang_med_innholdsproduksjon}  
2. {link_dokumentasjonskonvensjoner}
3. {link_konsepter_og_prinsipper}