= Nasjonalt virksomhetsarkitekturbibliotek

== Bakgrunn
Dette GitHub-biblioteket er opprettet av Difi våren 2018 for å samle dokumentasjon om virksomhetsarkitektur i offentlig sektor i Norge.

Github som lagringssted er en praktisk tilnærming og kan bli gjenstand for endring:  

== Struktur
Biblioteket er bygget opp etter mønster av TOGAF og Norsk arkitekturrammeverk for samhandling, der det skilles mellom arkitekturbibliotek, løsningsbibliotek og kravbibliotek.

[NOTE]
====
Navnet __arkitekturbibliotek__ henspeiler altså bare på en del av det totale biblioteket. For å presisere denne forskjellen, brukes betegnelsen __Nasjonalt virksomhetsarkitekturbibliotek__, der __virksomheten__ i dette tilfellet er (offentlig sektor i) Norge. 

__Til vurdering: Renavn og kall det bare arkitekturer, løsninger og krav, så fungerer det bedre å kalle det hele for [underline]#__arkitekturbibliotek__# -  trolig  enklere å forholde seg til for de fleste?__
====

== Innhold  vs. presentasjon
Innholdet dreier seg mye __samhandlingsarkitektur__, men er ikke begrenset til dette. Det er i utgangspunktet plass til all arkitekturdokumentasjon som kan være nyttig på tvers av virksomheter og sektorer. 

I tillegg til innhold her, vil det finnes mye stoff i tilsvarende biblioteker i enkelte virksomhetene som også kan være av felles interesse. Det er et siktemål at alle virksomheter følger samme struktur, retningslinjer og standarder for arkitekturdokumentasjon, slik at det blir enklere å referere og integrere innhold på tvers. 

Selv om høy kvalitet tilstrebes, skal terskelen for å publisere innhold i det nasjonale biblioteket ikke være uoverstigelig. I mangel av etablerte referansearkitekturer, vil en f.eks. forsøke å få på plass  eksempler på hvordan det er gjort hos de som har gode eksemplker å vise fram.  

== Dokumentasjonsformater og standarder - kort introduksjon
Et viktig prinsipp for dette biblioket, er å skille mellom innhold og presentasjon.  Alt nytt innhold skal produseres på   gjeldende standard innholdsformater. Dette er blant annet asciidoc for tekst og archimate utvekslingsformat for arkitekturmodeller. Ut fra standardformatene i biblioteket kan det enkelt konverteres til andre formater for presentasjon eller arbeid i egne verktøy.   Mer informasjon om standarder og retningslinjer finnes her: __Link kommer__.

Tidligere doumentasjon i andre formater konvereres til gjeldende standarder ut fra kost-nytte-vurderinger. Det finnes f.eks. verktøy for konverting av Word-dokumenter til asciidoc, men noe manuelt arbeid må en uansett regne med. For f.eks. Powerpoint eller wiki-innhold i Sharepoint eller Drupal, er saken en helt annen - her må en regne med å gjøre det meste manuelt.  

NOTE: Det er mulig å lagre tradisjonelle dokumenter på github, slik som f.eks Word eller pdf, men dette bør gjøres i begrenset grad som del av dette biblioteket. Total størrelse på Github-biblioteket bør ikke ovestige noen hundre MB; det vil ellers bli uegnet for kloning til lokale filområder, slik det må gjøres med github.  

== Verktøy
Det er opp til hver enkelt å velge produksjonsverktøy, så lenge resultatet er innhold på gjeldende standardformater. Det gis likevel tips og anbefalinger, slik at det skal bli enklere for hver enkelt å komme igang og følge de aktuelle standardene.


== Samarbeid
For å lykkes med dette, kreves utstrakt samarbeid. Gi beskjed via e-post til nasjonal.arkitektur@difi.no om du ønsker skrivetilgang.


== Annet
Mer om konsepter, standarder, retningslinjer, anbefalinger og tips finnes her: __Lenke kommer__
