= Nasjonal arkitektur: Bibliotek for virksomhetsarkitektur i Norge  
Difi, 2018-08-01

== Bakgrunn og formål
Dette GitHub-biblioteket er opprettet av Difi våren 2018 for å samle dokumentasjon om virksomhetsarkitektur i offentlig sektor i Norge.

Det legges opp til utstrakt samarbeid for å etablere og vedlikeholde innhold i biblioteket. Ditt bidra er ønsket. Gi beskjed via e-post til nasjonal.arkitektur@difi.no for å be om skrivetilgang.


== Omfang og avgrensing
Innholdet dreier seg primært om __samhandlingsarkitektur__, men er ikke begrenset til dette. All arkitekturdokumentasjon som kan være nyttig på tvers av virksomheter og sektorer hører hjemme her. 

I tillegg til innholdet i dette biblioteket, vil det finnes mye stoff i tilsvarende biblioteker i de enkelte virksomhetene som også kan være av felles interesse. 

Det er et siktemål at alle virksomheter følger et sett av  retningslinjer for arkitekturdokumentasjon som gjør det enkelt å referere og integrere innhold på tvers.

== Ditt bidrag er ønsket
Høy kvalitet tilstrebes, men terskelen for å publisere innhold i det nasjonale biblioteket skal ikke være for høy. Eksempler og god praksis må deles for å få fra beste praksis, anbefalinger, retningslinjer og standarder. 

Det skal være enkelt å komme i gang med å bidra til innholdocumentd i dette biblioteket. Se [red yellow-background]#<<document-b.adoc#section-b,Tips for å komme i gang>>#.
////
* <<document-b.adoc#section-b,Tips for å skrive artikler>>.
* <<document-b.adoc#section-b,Tips for å skrive dokumenter og bøker>>.
////


== Grunnleggende konsepter og prinsipper
Grunnleggende konsepter og prinsipper:

* Skille mellom innhold og presentasjon - standardformat for innhold i biblioteket, som så kan oversettes til vilkårlig format for plublisering eller videre arbeid   
* Levende dokumentasjon - alt skal kunne oppdateres løpende, uten å ødelegge sammenheng og konsistens  
* Versjonering og historikk - det må være mulig å gå tilbake og se tidligere versjoner

Se [red yellow-background]#<<document-b.adoc#section-b,Konsepter, prinsipper og funksjonelle krav>># for mer informasjon.

== Struktur
Mappestrukturen i biblioteket er bygget opp etter mønster av TOGAF og Norsk arkitekturrammeverk for samhandling.  

En kan også tagge innhold med metadata og bruke dette for å navigere og søke.

== Standarder, retningslinjer og anbefalinger
=== Dokumentasjonsformater
Alt nytt innhold skal lagres på gjeldende standard innholdsformater. Dette er blant annet Asciidoc for tekst og Archimate utvekslingsformat for arkitekturmodeller.

Ut fra standardformatene i biblioteket kan det enkelt konverteres til andre formater for publisering eller videre arbeid. For publisering benyttes i utgangspunktet primært html5.

Tidligere dokumentasjon i andre formater konvereres til gjeldende standarder ut fra kost-nytte-vurderinger. Det finnes f.eks. verktøy for konverting av Word-dokumenter til asciidoc, men noe manuelt arbeid må en uansett regne med.  

NOTE: Det er mulig å lagre tradisjonelle dokumenter på github, slik som f.eks Word eller pdf, men dette gjøres i minst mulig grad. Andre teknologier er bedre egnet enn GitHub for lagring og søk i dokumenter. Total størrelse på Github-biblioteket bør dessuten begrenses, slik at det lar seg klone til den enkeltes lokale filområde (det er slik en jobber med innhold i github). 

=== Annet
Se [red yellow-background]#<<document-b.adoc#section-b,standarder, retningslinjer og anbefalinger>># for mer informasjon.


