// Tips: lang-attributten settes normalt fra asciidoctor kommandolinjen som f.eks."-a lang=en". I så fall overstyres parametersettingen som gjøres her; dvs. at følgende setting ":lang: no" kun fungerer som defaultverdi (nyttig for visning i WYSIWIG-editor)
:lang: en 
:revdate: 2018-08-06
ifeval::["{lang}" == "no"]
= Tips om dokumentasjon på GitHub
Direktoratet for fovaltning og ikt (Difi)
{revdate} 
:revremark: Initiell versjon
:keywords: GitHub, dokumentasjon
endif::[]
ifeval::["{lang}" == "en"]
= How to for GitHub documentation
Agency for Public Management and eGovernment (Difi)
{revdate}
:revremark: Initial revision
:keywords: GitHub, documentation
endif::[]
:description: Hvordan komme i gang - standarder - retningslinjer - praktiske tips
:doctype: article
:icons: font
//:docinfodir: meta
//:docinfo:
:toc: macro
//:sectnums:
:leveloffset: +0
:toc-title: Innhold
:toclevels: 3
:sectlinks:
:sectids:
:sectanchors:
:sectnumlevels: 3
:xrefstyle: short
:imagesdir: images
// data-uri benyttes for å inkludere images i generert html-fil 
:data-uri: 

ifeval::["{toc}" == "macro"]
toc::[]
endif::[]
// Note, Erik, 2018-08-11: Seems tricky to get the macro toc displayed; e.g. can't have it below the following logo image? So, go for ":toc: left" for now...

image:difilogo.svg[image,width=169,height=66]

ifeval::["{lang}" == "en"]
_For english speakers: This document was originally written in the Norwegian language. The English translation may be incomplete._ 
endif::[]


//include::locale/attributes.adoc[]

== Komme igang


=== Etabler lokal filmappe for kloning av github-filer

Lag en filmappe som hjemmeområde for å arbeide lokalt med github-filer.

NOTE: Om du bruker lange navn og dyp mappestruktur i Windows, kan du få problemer med en begrensning på 260
karakterer i total lengde på filnavn. I og med Windows 10 kan denne begrensningen oppheves. Se f.eks.
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/ for en oppskrift på
hvordan dette kan gjøres. +
 +
Kort fortalt: På Windows 10 Enterprise kan du kjøre gpedit.msc og endre Aktiver lange Win32 baner under
Datamaskinkonfigurasjon, Administrative maler, System, Filsystem. Du må restarte eller logge av og på for at endringen skal tre i kraft. +
 +
_Men fungerer dette med GitHub?_


=== Installer GitHub Desktop

NOTE: GitHub desktop kan av og til ha problemer med å aksessere .gitconfig-filen. Dette kan trolig fikses ved å opprette en systemvariabel HOME til den mappen du har opprettet som
hjemmeområde for dine lokale GitHub-filer (bruk Kontrollpanel, System, Avanserte systeminnstillinger, miljøvariabler). +
 +
Tips: Det er kanskje en god ide å unngå å bruke nettverks-drive (som noen virksomheter bruker som default for Dokumenter)? Bruk kanskje heller en katalog direkte under ditt brukernavn på C:\Users? Se også  https://github.com/desktop/desktop/issues/4119.


=== Installer redigeringsverktøy
Flere verktøy for editering av asciidoc finnes. De fleste vil ha nytte av en editor som gir støtte til formatering og viser resultatet direkte (WYSIWIG).

. AsciidocFX
. Eventuelt også Atom , Teletype for Atom (?)

=== Installer verktøy for formatkonvertering
. pandoc

=== Klon GitHub-prosjektet til din maskin

Med Github desktop: File | Clone a repository

=== Skriv et dokument som dette

Antar her AsciidocFX som editor, slik dette virker per august 2018.

Tips:

* Start med å kopiere denne malen:  (Kommer)
* Unngå å endre de første linjene (_header_) før du vet hva du gjør. Et linjeskift for mye eller for lite her kan endre innhold og utseende og gi problemer for plassering av innholdsfortegnelse.
* Bruk asciidoctor kommandolinje for å styre språk (standardattributt _lang_)
* Bruk asciidoctor kommandolinje for å styre plassering av innholdsfortegnelse (standardattributt _toc_)
* 
