= Tips om bruk av github for Nasjonal arkitektur

=== Komme igang

Lag en filmappe som hjemmeområde for å arbeide lokalt med github-filer.

NOTE: Om du bruker lange navn og dyp mappestruktur i Windows, kan du få problemer med en begrensning på 260
karakterer i total lengde på filnavn. I og med Windows 10 kan denne begrensningen oppheves. Se f.eks.
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/ for en oppskrift på
hvordan dette kan gjøres. Kort fortalt: På Windows 10 Enterprise kan du kjøre gpedit.msc og endre Aktiver lange Win32 baner under
Datamaskinkonfigurasjon, Administrative maler, System, Filsystem. Du må restarte eller logge av og på for at endringen skal tre i kraft.


=== Installer GitHub Desktop

NOTE: GitHub desktop kan av og til ha problemer med å aksessere .gitconfig-filen. Dette kan trolig fikses ved å opprette en systemvariabel HOME til den mappen du har opprettet som
hjemmeområde for dine lokale GitHub-filer (bruk Kontrollpanel, System, Avanserte systeminnstillinger, miljøvariabler). NB! En bør kanskje unngå å bruke nettverks-drive (som noen virksomheter bruker som default for Dokumenter). Bruk da heller en katalog direkte under ditt brukernavn på C:\Brukere. Se også  https://github.com/desktop/desktop/issues/4119. 



=== Klon GitHub-prosjektet til din maskin

Med Github desktop: File | Clone a repository


. Atom

. Teletype for Atom (?)
