// Tips: lang-attributten settes normalt fra asciidoctor kommandolinjen som f.eks."-a lang=en". I så fall overstyres parametersettingen som gjøres her; dvs. at følgende setting ":lang: no" kun fungerer som defaultverdi (nyttig for visning i WYSIWIG-editor)
:lang: no 
ifeval::["{lang}" == "no"]
= Tips om dokumentasjon på GitHub
endif::[]
ifeval::["{lang}" == "en"]
= How to for GitHub documentation
endif::[]

Direktoratet for forvaltning og IKT

//:description: Hvordan komme i gang - standarder - retningslinjer - praktiske tips

:doctype: article
:icons: font
//:docinfodir: meta
:docinfo:

//:sectnums:
:leveloffset: +0
//:toc: macro
:toc: left
:toc-title: Innhold
:toclevels: 3
:sectlinks:
:sectids:
:sectanchors:
:sectnumlevels: 3
:xrefstyle: short
:imagesdir: images
// data-uri benyttes for å inkludere images i generert html-fil 
:data-uri: 

:SistEndretDato: 2018-08-06 
//Erik: Sjekk om det finnes en standardattributt som gir SistEndretDatos automatisk

// extended-lang-processing er en egendefinert attributt (Difi) som trigger utvidet språkstøtte. Se også lang1, lang2 
:extended-lang-processing: yes

// egendefinert attributt (Difi) for å angi hvilket språk artikkelen eller boken først ble skrevet på. Interesseant å vite dersom oversettelse til f.eks. engelsk fra norsk bare er delvis gjort
:lang1: no

// egendefinert attributt (Difi) for å angi et språk nr. 2 som det er oversatt til, helt eller delvis
:lang2: en

// egendefinert attributt (Difi) for å angi et språk nr. 3 som det er oversatt til, helt eller delvis
:lang3: dk


// egendefinert attributt (Difi) for å angi om oversettelsen til språk 2 er komplett. Verdier: no; yes 
:lang2complete: no




image:difilogo.svg[image,width=169,height=66]

Dato: {sistEndretDato} 


ifeval::["{lang2complete}" == "no"]
//
ifeval::["{lang}" == "en"]
_For english speakers: This document was originally written in the Norwegian language. Only som parts of the document has so far been translated into English._ 
endif::[]
//
endif::[]




ifeval::["{toc}" == "macro"]
toc::[]
endif::[]

//include::locale/attributes.adoc[]

== Komme igang


=== Etabler lokal filmappe for kloning av github-filer

Lag en filmappe som hjemmeområde for å arbeide lokalt med github-filer.

NOTE: Om du bruker lange navn og dyp mappestruktur i Windows, kan du få problemer med en begrensning på 260
karakterer i total lengde på filnavn. I og med Windows 10 kan denne begrensningen oppheves. Se f.eks.
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/ for en oppskrift på
hvordan dette kan gjøres. +
 +
Kort fortalt: På Windows 10 Enterprise kan du kjøre gpedit.msc og endre Aktiver lange Win32 baner under
Datamaskinkonfigurasjon, Administrative maler, System, Filsystem. Du må restarte eller logge av og på for at endringen skal tre i kraft. +
 +
_Men fungerer dette med GitHub?_


=== Installer GitHub Desktop

NOTE: GitHub desktop kan av og til ha problemer med å aksessere .gitconfig-filen. Dette kan trolig fikses ved å opprette en systemvariabel HOME til den mappen du har opprettet som
hjemmeområde for dine lokale GitHub-filer (bruk Kontrollpanel, System, Avanserte systeminnstillinger, miljøvariabler). +
 +
Tips: Det er kanskje en god ide å unngå å bruke nettverks-drive (som noen virksomheter bruker som default for Dokumenter)? Bruk kanskje heller en katalog direkte under ditt brukernavn på C:\Users? Se også  https://github.com/desktop/desktop/issues/4119.


=== Installer redigeringsverktøy
Flere verktøy for editering av asciidoc finnes. De fleste vil ha nytte av en editor som gir støtte til formatering og viser resultatet direkte (WYSIWIG).

. AsciidocFX
. Eventuelt også Atom , Teletype for Atom (?)

=== Installer verktøy for formatkonvertering
. pandoc

=== Klon GitHub-prosjektet til din maskin

Med Github desktop: File | Clone a repository
