= Identifisering av samhandlingsmønstre

Digital samhandling mellom virksomheter kan utføres på et begrenset antall måter sett fra et forretningsståsted. Vi vil videre kalle dette samhandlingsmønstre. Samhandlingsmønstre sier ikke noe om hvilken teknologi som skal benyttes, men sier noe om hvilken egenskap samhandlingen skal ha. Det er til nå identifisert 7 forskjellige samhandlingsmønstre.

Mønstre samhandling.png

Hvert enkelt samhandlingsmønster beskrives under i mer detalj. I beskrivelsen finner man referanse til tilsvarende samhandlingsmønstre (patterns) som er definert av andre:

* UMM Transaction patterns (UN/CEFACT's Modeling Methodology - UMM)
* Enterprise Integration Patterns (EAI) (Gregor Hohpe og Bobby Woolf)

For hvert samhandlingsmønster pekes det på hvilken referansearkitektur som skal benyttes for samhandlingen.


1. Forretningstransaksjon mellom to parter
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


2. Oversende informasjonsendring til informasjonseier
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



3. Oversende informasjon mellom to parter
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 

4. Forespørsel om informasjon mellom to parter – "umiddelbar" respons
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


5. Notifikasjon til identifisert part
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 

6. Notifikasjon til mange
~~~~~~~~~~~~~~~~~~~~~~~~~~
 

7. Forespørsel om informasjon mellom to parter – ikke "umiddelbar" respons
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
